package assumptions

import (
	"fmt"
	"strings"
)

// System profile identities form an append-only, immutable chain. Each published
// identity's canonical content is frozen forever; correcting the model or its
// evidence must publish a NEW identity rather than editing a released one in place.
// The history:
//
//   - system_cma_v1@1: original CNY-only seed priors.
//   - system_cma_v2@1: added native USD/HKD priors + tail truncation, but
//     its nominal returns used an additive (non-geometric) shortcut.
//   - system_cma_v3@1: same structure, but every return/FX prior is the
//     EXACT compounded value built from the committed CMA evidence artifact.
//   - system_cma_v4@1: keeps the v3 numeric policy, corrects its provenance and
//     fee/FX wording, and versions same-type asset correlation priors.
//
// v1 and v2 are never generated by code anymore: they only live in already-upgraded
// databases (for replay and explicit pins). EnsureSystemDefault publishes and
// migrates to the current identity only.
const (
	// SystemProfileID / SystemProfileVersion are the CURRENT default system
	// identity. Code that resolves "the system default" uses these.
	SystemProfileID      = "system_cma_v4"
	SystemProfileVersion = 1

	SystemProfileV3ID      = "system_cma_v3"
	SystemProfileV3Version = 1

	// SystemProfileV2ID / V2Version is the frozen v2 identity (direct
	// predecessor of v3 and predecessor chain leading to the current identity).
	SystemProfileV2ID      = "system_cma_v2"
	SystemProfileV2Version = 1

	// SystemLegacyProfileID / Version is the original v1 identity. It is
	// never updated or deleted so old runs and v1 pins replay exactly.
	SystemLegacyProfileID      = "system_cma_v1"
	SystemLegacyProfileVersion = 1
)

// SystemProfileIDPrefix is the reserved id namespace for system-owned profiles.
// A user profile may NEVER use an id with this prefix, otherwise it could shadow a
// system identity in the (id, version)-keyed table and steal its CMA evidence
// provenance.
const SystemProfileIDPrefix = "system_cma_"

// HasReservedSystemID reports whether an id is in the reserved system namespace.
func HasReservedSystemID(id string) bool {
	return strings.HasPrefix(id, SystemProfileIDPrefix)
}

// Pinned canonical/evidence SHA-256 for every published system identity. These are
// asserted in tests: editing the current evidence artifact (or the built canonical
// content) without publishing a new identity and updating this registry fails CI.
// v1/v2 hashes are the byte-exact hashes of their released
// canonical JSON (see internal/repository/testdata).
const (
	systemProfileV1CanonicalHash = "6eecc14f7c8c8f812382e9cea88b7c056c18db8e6fd1a832961e63dd66f0971c"
	// systemProfileV2CanonicalHash is the TD 064 published v2 canonical content.
	systemProfileV2CanonicalHash = "3a1545466b5f40856706e66952a3cad26ef546a929e181949727b96dbd143698"
	// systemProfileV2TD065CanonicalHash is the v2 VARIANT briefly built from
	// cma_evidence_v2.json during TD 065 (commit 9700d69) under the same v2 identity.
	// Databases first initialized on that build hold this content.
	systemProfileV2TD065CanonicalHash = "732e64f958bf5d48b6089516cf546b356537b34b23e7fdd7798079a3ac7af570"
	systemProfileV2TD065EvidenceHash  = "079d7844f2a365771895db97f4e3d5b1388ce6ea23ec6969be86725a9d5bce22"
	systemProfileV3CanonicalHash      = "27fdbe1790afb5b0f75ec780472e4426abce1f46e966dc689f9dd0dd04cf2886"
	systemProfileV3EvidenceHash       = "6cc582c4b0a1695199f09c9dc24b0f5d22df3af13cf08f6bc4fe6bef2c119eb2"
	systemProfileV4CanonicalHash      = "c563c0a414564aaffe1cbb21c2f6c6f8d979ec593d627df6c255602791df735c"
	systemProfileV4EvidenceHash       = "df3c0203eeccd79c4fcccd76cac779e1b129f094e9eef7e0de6c675b22e2a473"
)

// SystemProfileIdentity is one immutable entry in the system-profile registry.
type SystemProfileIdentity struct {
	ID            string
	Version       int
	CanonicalHash string // frozen SHA-256 of the canonical JSON
	EvidenceHash  string // SHA-256 of the backing evidence artifact ("" if none)
	Predecessor   string // "id@version" of the direct predecessor ("" for the first)
}

// Ref returns the "id@version" reference for this identity.
func (e SystemProfileIdentity) Ref() string {
	return profileRef(e.ID, e.Version)
}

var systemProfileRegistry = []SystemProfileIdentity{
	{ID: SystemLegacyProfileID, Version: SystemLegacyProfileVersion, CanonicalHash: systemProfileV1CanonicalHash},
	{
		ID: SystemProfileV2ID, Version: SystemProfileV2Version, CanonicalHash: systemProfileV2CanonicalHash,
		Predecessor: profileRef(SystemLegacyProfileID, SystemLegacyProfileVersion),
	},
	{
		ID: SystemProfileV3ID, Version: SystemProfileV3Version,
		CanonicalHash: systemProfileV3CanonicalHash, EvidenceHash: systemProfileV3EvidenceHash,
		Predecessor: profileRef(SystemProfileV2ID, SystemProfileV2Version),
	},
	{
		ID: SystemProfileID, Version: SystemProfileVersion,
		CanonicalHash: systemProfileV4CanonicalHash, EvidenceHash: systemProfileV4EvidenceHash,
		Predecessor: profileRef(SystemProfileV3ID, SystemProfileV3Version),
	},
}

// SystemProfileRegistry returns the immutable system-profile identity chain.
func SystemProfileRegistry() []SystemProfileIdentity {
	out := make([]SystemProfileIdentity, len(systemProfileRegistry))
	copy(out, systemProfileRegistry)
	return out
}

// CurrentSystemIdentity is the registry entry for the current default identity.
func CurrentSystemIdentity() SystemProfileIdentity {
	return systemProfileRegistry[len(systemProfileRegistry)-1]
}

// LookupSystemIdentity returns the registry entry for an id@version, if any.
func LookupSystemIdentity(id string, version int) (SystemProfileIdentity, bool) {
	for _, e := range systemProfileRegistry {
		if e.ID == id && e.Version == version {
			return e, true
		}
	}
	return SystemProfileIdentity{}, false
}

// IsCurrentSystemDefaultIdentity reports whether id@version is the current
// default-able system identity. A system-owned profile that is not the current
// identity can be used for replay or an explicit pin but can never
// be (re)selected as the global default.
func IsCurrentSystemDefaultIdentity(id string, version int) bool {
	cur := CurrentSystemIdentity()
	return id == cur.ID && version == cur.Version
}

// CurrentSystemPredecessorRef is the "id@version" of the direct predecessor of the
// current system identity, the only system default the upgrade auto-migrates
// from.
func CurrentSystemPredecessorRef() string {
	return CurrentSystemIdentity().Predecessor
}

// HistoricalSystemProfileVariant is one recognized, immutable published system
// profile CONTENT, keyed by (id, version, content_hash). Unlike the identity chain
// (one canonical content per identity), the variant registry also records contents
// that were briefly published under an already-used identity — notably the TD 065
// v2 variant. It is read-only: it backs historical replay/pin
// provenance and lets EnsureSystemDefault recognize a legitimate historical system
// row, but a variant can never become the global default.
type HistoricalSystemProfileVariant struct {
	ID            string
	Version       int
	CanonicalHash string
	EvidenceHash  string // backing CMA evidence artifact hash ("" if none)
	Note          string
}

// Ref returns the "id@version" reference for this variant.
func (v HistoricalSystemProfileVariant) Ref() string {
	return profileRef(v.ID, v.Version)
}

var historicalSystemProfileVariants = []HistoricalSystemProfileVariant{
	{
		ID: SystemLegacyProfileID, Version: SystemLegacyProfileVersion,
		CanonicalHash: systemProfileV1CanonicalHash,
		Note:          "original v1 (CNY-only seed priors)",
	},
	{
		ID: SystemProfileV2ID, Version: SystemProfileV2Version,
		CanonicalHash: systemProfileV2CanonicalHash,
		Note:          "published v2 (additive shortcut)",
	},
	{
		ID: SystemProfileV2ID, Version: SystemProfileV2Version,
		CanonicalHash: systemProfileV2TD065CanonicalHash,
		EvidenceHash:  systemProfileV2TD065EvidenceHash,
		Note:          "v2 variant built from cma_evidence_v2.json (commit 9700d69)",
	},
	{
		ID: SystemProfileV3ID, Version: SystemProfileV3Version,
		CanonicalHash: systemProfileV3CanonicalHash,
		EvidenceHash:  systemProfileV3EvidenceHash,
		Note:          "historical v3 (compounded, evidence-backed)",
	},
	{
		ID: SystemProfileID, Version: SystemProfileVersion,
		CanonicalHash: systemProfileV4CanonicalHash,
		EvidenceHash:  systemProfileV4EvidenceHash,
		Note:          "current v4 (internal policy, embedded ongoing fees)",
	},
}

// HistoricalSystemProfileVariants returns the read-only variant registry.
func HistoricalSystemProfileVariants() []HistoricalSystemProfileVariant {
	out := make([]HistoricalSystemProfileVariant, len(historicalSystemProfileVariants))
	copy(out, historicalSystemProfileVariants)
	return out
}

// LookupSystemContent returns the recognized system content for an exact
// (id, version, content_hash). It is the single source of truth for "is this
// system row a known, immutable published content" used by the startup upgrade
// guard and by run provenance.
func LookupSystemContent(id string, version int, contentHash string) (HistoricalSystemProfileVariant, bool) {
	for _, v := range historicalSystemProfileVariants {
		if v.ID == id && v.Version == version && v.CanonicalHash == contentHash {
			return v, true
		}
	}
	return HistoricalSystemProfileVariant{}, false
}

// RecognizedSystemContentHashes returns the set of recognized canonical content
// hashes for a given system id@version (e.g. both published v2 contents).
func RecognizedSystemContentHashes(id string, version int) []string {
	var out []string
	for _, v := range historicalSystemProfileVariants {
		if v.ID == id && v.Version == version {
			out = append(out, v.CanonicalHash)
		}
	}
	return out
}

func profileRef(id string, version int) string {
	return fmt.Sprintf("%s@%d", id, version)
}

// System profile review metadata.
// The provenance references the immutable CMA evidence artifact (version + content
// hash) that records, per prior, the specific source, raw inputs and EXACT
// geometric conversion to a CNY-nominal after-fee return. Any change to the inputs
// changes the artifact hash and must publish a NEW system profile identity.
var SystemProfileSourceNote = "Internal policy prior v4 (evidence_kind=internal_policy; sha256:" +
	CMAEvidenceContentHash[:12] + "; artifact=" + CMAEvidenceVersion +
	"). Values are FIRE planning policy assumptions, not directly published CNY " +
	"product-return forecasts. Research Affiliates and BIS are methodology/background references. Fund NAV and " +
	"profile returns are treated as already containing ongoing management/custody expenses; no expense ratio is " +
	"deducted again. CNY-valued foreign funds contain FX risk in NAV; native-currency assets use a separate FX factor."

const (
	SystemProfileReviewedBy = "FIRE 投研团队"
	SystemProfileReviewedAt = "2026-07-12"
)

// SystemDefaultProfile returns the current read-only system assumption profile
// used when a user has not configured a global profile. It must
// always pass Validate, including the minimum global coverage gate.
func SystemDefaultProfile() Profile {
	return Profile{
		ID:                        SystemProfileID,
		Version:                   SystemProfileVersion,
		OwnerScope:                OwnerSystem,
		Name:                      "系统默认（保守政策先验 v4）",
		Status:                    StatusActive,
		PriorStrengthYears:        20,
		CorrelationStrengthMonths: 36,
		StudentTDf:                7,
		// Per-month simple-return truncation band, owned by the profile so the tail
		// clamp is versioned and frozen into each run. These match the
		// historical engine constants so forward runs keep the same bound.
		ReturnFloor: -0.95,
		ReturnCeil:  2.0,
		Scenarios: map[string]Scenario{
			ScenarioConservative: {ReturnShiftLog: -0.015, ReturnShiftLogFX: 0, VolatilityMultiplier: 1.15},
			ScenarioBaseline:     {ReturnShiftLog: 0, ReturnShiftLogFX: 0, VolatilityMultiplier: 1.00},
			ScenarioOptimistic:   {ReturnShiftLog: 0.015, ReturnShiftLogFX: 0, VolatilityMultiplier: 0.90},
		},
		// Return and FX priors are materialized from the immutable CMA evidence
		// artifact: each value is the EXACT compounded
		// return rounded to 4 decimals, traced to a specific dated source. Native
		// USD/HKD priors let an asset priced in its own currency calibrate its local
		// return without an FX mismatch; the FX priors carry the currency view
		// separately and share the equity:foreign / bond:foreign factor.
		ReturnPriors:      buildSystemReturnPriors(),
		FXPriors:          buildSystemFXPriors(),
		CorrelationPriors: systemCorrelationPriors(),
	}
}

// systemCorrelationPriors returns one prior for every distinct pair of random
// factors (deterministic cash is excluded from the universe, so it carries no
// correlation prior). The six factors — domestic/foreign equity, domestic/foreign
// bond and the USD/CNY and HKD/CNY FX factors — yield the full set of C(6,2)=15
// pairs required by Profile.Validate. HKD is USD-pegged, so its FX
// factor mirrors USD/CNY's correlations and is near-perfectly correlated with it.
func systemCorrelationPriors() []CorrelationPrior {
	eqD := AssetFactorKey("equity", "domestic")
	eqF := AssetFactorKey("equity", "foreign")
	bdD := AssetFactorKey("bond", "domestic")
	bdF := AssetFactorKey("bond", "foreign")
	fxUSD := FXFactorKey("USD", "CNY")
	fxHKD := FXFactorKey("HKD", "CNY")
	return []CorrelationPrior{
		{FactorA: eqD, FactorB: eqD, Rho: 1.00},
		{FactorA: eqF, FactorB: eqF, Rho: 1.00},
		{FactorA: bdD, FactorB: bdD, Rho: 1.00},
		{FactorA: bdF, FactorB: bdF, Rho: 1.00},
		{FactorA: eqD, FactorB: eqF, Rho: 0.60},
		{FactorA: eqD, FactorB: bdD, Rho: 0.15},
		{FactorA: eqD, FactorB: bdF, Rho: 0.10},
		{FactorA: eqF, FactorB: bdD, Rho: 0.10},
		{FactorA: eqF, FactorB: bdF, Rho: 0.20},
		{FactorA: bdD, FactorB: bdF, Rho: 0.40},
		{FactorA: eqF, FactorB: fxUSD, Rho: 0.15},
		{FactorA: eqD, FactorB: fxUSD, Rho: 0},
		{FactorA: bdD, FactorB: fxUSD, Rho: 0},
		{FactorA: bdF, FactorB: fxUSD, Rho: 0},
		{FactorA: eqF, FactorB: fxHKD, Rho: 0.15},
		{FactorA: eqD, FactorB: fxHKD, Rho: 0},
		{FactorA: bdD, FactorB: fxHKD, Rho: 0},
		{FactorA: bdF, FactorB: fxHKD, Rho: 0},
		{FactorA: fxUSD, FactorB: fxHKD, Rho: 0.95},
	}
}
