package assumptions

import "fmt"

// System profile identities form an append-only, immutable chain. Each published
// identity's canonical content is frozen forever; correcting the model or its
// evidence must publish a NEW identity rather than editing a released one in place
// (td/064 R6, td/066 R12). The history:
//
//   - system_cma_v1@1 (td/061/062): original CNY-only seed priors.
//   - system_cma_v2@1 (td/064): added native USD/HKD priors + tail truncation, but
//     its nominal returns used an additive (non-geometric) shortcut (td/066 R11).
//   - system_cma_v3@1 (td/066): same structure, but every return/FX prior is the
//     EXACT compounded value built from the committed CMA evidence artifact.
//
// v1 and v2 are never generated by code anymore: they only live in already-upgraded
// databases (for replay and explicit pins). EnsureSystemDefault publishes and
// migrates to the current identity (v3) only.
const (
	// SystemProfileID / SystemProfileVersion are the CURRENT default system
	// identity. Code that resolves "the system default" uses these.
	SystemProfileID      = "system_cma_v3"
	SystemProfileVersion = 1

	// SystemProfileV2ID / V2Version is the frozen td/064 identity (direct
	// predecessor of v3).
	SystemProfileV2ID      = "system_cma_v2"
	SystemProfileV2Version = 1

	// SystemLegacyProfileID / Version is the original td/061/062 identity. It is
	// never updated or deleted so old runs and v1 pins replay exactly.
	SystemLegacyProfileID      = "system_cma_v1"
	SystemLegacyProfileVersion = 1
)

// Pinned canonical/evidence SHA-256 for every published system identity. These are
// asserted in tests: editing the v3 evidence artifact (or the built canonical
// content) without publishing a new identity and updating this registry fails CI
// (td/066 R12 §3). v1/v2 hashes are the byte-exact hashes of their released
// canonical JSON (see internal/repository/testdata).
const (
	systemProfileV1CanonicalHash = "6eecc14f7c8c8f812382e9cea88b7c056c18db8e6fd1a832961e63dd66f0971c"
	systemProfileV2CanonicalHash = "3a1545466b5f40856706e66952a3cad26ef546a929e181949727b96dbd143698"
	systemProfileV3CanonicalHash = "27fdbe1790afb5b0f75ec780472e4426abce1f46e966dc689f9dd0dd04cf2886"
	systemProfileV3EvidenceHash  = "6cc582c4b0a1695199f09c9dc24b0f5d22df3af13cf08f6bc4fe6bef2c119eb2"
)

// SystemProfileIdentity is one immutable entry in the system-profile registry.
type SystemProfileIdentity struct {
	ID            string
	Version       int
	CanonicalHash string // frozen SHA-256 of the canonical JSON
	EvidenceHash  string // SHA-256 of the backing evidence artifact ("" if none)
	Predecessor   string // "id@version" of the direct predecessor ("" for the first)
}

// Ref returns the "id@version" reference for this identity.
func (e SystemProfileIdentity) Ref() string {
	return profileRef(e.ID, e.Version)
}

var systemProfileRegistry = []SystemProfileIdentity{
	{ID: SystemLegacyProfileID, Version: SystemLegacyProfileVersion, CanonicalHash: systemProfileV1CanonicalHash},
	{
		ID: SystemProfileV2ID, Version: SystemProfileV2Version, CanonicalHash: systemProfileV2CanonicalHash,
		Predecessor: profileRef(SystemLegacyProfileID, SystemLegacyProfileVersion),
	},
	{
		ID: SystemProfileID, Version: SystemProfileVersion,
		CanonicalHash: systemProfileV3CanonicalHash, EvidenceHash: systemProfileV3EvidenceHash,
		Predecessor: profileRef(SystemProfileV2ID, SystemProfileV2Version),
	},
}

// SystemProfileRegistry returns the immutable system-profile identity chain.
func SystemProfileRegistry() []SystemProfileIdentity {
	out := make([]SystemProfileIdentity, len(systemProfileRegistry))
	copy(out, systemProfileRegistry)
	return out
}

// CurrentSystemIdentity is the registry entry for the current default identity.
func CurrentSystemIdentity() SystemProfileIdentity {
	return systemProfileRegistry[len(systemProfileRegistry)-1]
}

// LookupSystemIdentity returns the registry entry for an id@version, if any.
func LookupSystemIdentity(id string, version int) (SystemProfileIdentity, bool) {
	for _, e := range systemProfileRegistry {
		if e.ID == id && e.Version == version {
			return e, true
		}
	}
	return SystemProfileIdentity{}, false
}

// IsCurrentSystemDefaultIdentity reports whether id@version is the current
// default-able system identity (v3). A system-owned profile that is not the
// current identity (v1/v2) can be used for replay or an explicit pin but can never
// be (re)selected as the global default (td/066 R12).
func IsCurrentSystemDefaultIdentity(id string, version int) bool {
	cur := CurrentSystemIdentity()
	return id == cur.ID && version == cur.Version
}

// CurrentSystemPredecessorRef is the "id@version" of the direct predecessor of the
// current system identity (v2), the only system default the upgrade auto-migrates
// from.
func CurrentSystemPredecessorRef() string {
	return CurrentSystemIdentity().Predecessor
}

func profileRef(id string, version int) string {
	return fmt.Sprintf("%s@%d", id, version)
}

// System profile review metadata (td/063 N1 / td/064 N5 / td/065 R10 / td/066 R11).
// The provenance references the immutable CMA evidence artifact (version + content
// hash) that records, per prior, the specific source, raw inputs and EXACT
// geometric conversion to a CNY-nominal after-fee return. Any change to the inputs
// changes the artifact hash and must publish a NEW system profile identity.
var SystemProfileSourceNote = "CMA v3: conservative, after-fee, CNY-nominal geometric return priors " +
	"reproducible from the committed evidence artifact " + CMAEvidenceVersion +
	" (sha256:" + CMAEvidenceContentHash[:12] + "). Returns compound real growth with expected inflation " +
	"net of fees: (1+real)*(1+pi)*(1-fee)-1; FX uses (1+pi_base)/(1+pi_quote)-1. Asset real returns from " +
	"Research Affiliates' Asset Allocation Interactive and FX from BIS exchange-rate statistics, signed off " +
	"by the FIRE investment team. See internal/assumptions/cma_evidence_v3.json for the per-prior derivation."

const (
	SystemProfileReviewedBy = "FIRE 投研团队 (CMA v3 sign-off)"
	SystemProfileReviewedAt = "2026-06-20"
)

// SystemDefaultProfile returns the current read-only system assumption profile
// (system_cma_v3@1) used when a user has not configured a global profile. It must
// always pass Validate, including the minimum global coverage gate (td/064 R7).
func SystemDefaultProfile() Profile {
	return Profile{
		ID:                        SystemProfileID,
		Version:                   SystemProfileVersion,
		OwnerScope:                OwnerSystem,
		Name:                      "系统默认（CMA v3）",
		Status:                    StatusActive,
		PriorStrengthYears:        20,
		CorrelationStrengthMonths: 36,
		StudentTDf:                7,
		// Per-month simple-return truncation band, owned by the profile so the tail
		// clamp is versioned and frozen into each run (td/063 R3). These match the
		// historical engine constants so forward runs keep the same bound.
		ReturnFloor: -0.95,
		ReturnCeil:  2.0,
		Scenarios: map[string]Scenario{
			ScenarioConservative: {ReturnShiftLog: -0.015, ReturnShiftLogFX: 0, VolatilityMultiplier: 1.15},
			ScenarioBaseline:     {ReturnShiftLog: 0, ReturnShiftLogFX: 0, VolatilityMultiplier: 1.00},
			ScenarioOptimistic:   {ReturnShiftLog: 0.015, ReturnShiftLogFX: 0, VolatilityMultiplier: 0.90},
		},
		// Return and FX priors are materialized from the immutable CMA evidence
		// artifact (td/065 R10 / td/066 R11): each value is the EXACT compounded
		// return rounded to 4 decimals, traced to a specific dated source. Native
		// USD/HKD priors let an asset priced in its own currency calibrate its local
		// return without an FX mismatch; the FX priors carry the currency view
		// separately (td/063 R2) and share the equity:foreign / bond:foreign factor.
		ReturnPriors:      buildSystemReturnPriors(),
		FXPriors:          buildSystemFXPriors(),
		CorrelationPriors: systemCorrelationPriors(),
	}
}

// systemCorrelationPriors returns one prior for every distinct pair of random
// factors (deterministic cash is excluded from the universe, so it carries no
// correlation prior). The six factors — domestic/foreign equity, domestic/foreign
// bond and the USD/CNY and HKD/CNY FX factors — yield the full set of C(6,2)=15
// pairs required by Profile.Validate (td/063 R4). HKD is USD-pegged, so its FX
// factor mirrors USD/CNY's correlations and is near-perfectly correlated with it.
func systemCorrelationPriors() []CorrelationPrior {
	eqD := AssetFactorKey("equity", "domestic")
	eqF := AssetFactorKey("equity", "foreign")
	bdD := AssetFactorKey("bond", "domestic")
	bdF := AssetFactorKey("bond", "foreign")
	fxUSD := FXFactorKey("USD", "CNY")
	fxHKD := FXFactorKey("HKD", "CNY")
	return []CorrelationPrior{
		{FactorA: eqD, FactorB: eqF, Rho: 0.60},
		{FactorA: eqD, FactorB: bdD, Rho: 0.15},
		{FactorA: eqD, FactorB: bdF, Rho: 0.10},
		{FactorA: eqF, FactorB: bdD, Rho: 0.10},
		{FactorA: eqF, FactorB: bdF, Rho: 0.20},
		{FactorA: bdD, FactorB: bdF, Rho: 0.40},
		{FactorA: eqF, FactorB: fxUSD, Rho: 0.15},
		{FactorA: eqD, FactorB: fxUSD, Rho: 0},
		{FactorA: bdD, FactorB: fxUSD, Rho: 0},
		{FactorA: bdF, FactorB: fxUSD, Rho: 0},
		{FactorA: eqF, FactorB: fxHKD, Rho: 0.15},
		{FactorA: eqD, FactorB: fxHKD, Rho: 0},
		{FactorA: bdD, FactorB: fxHKD, Rho: 0},
		{FactorA: bdF, FactorB: fxHKD, Rho: 0},
		{FactorA: fxUSD, FactorB: fxHKD, Rho: 0.95},
	}
}
